apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongo.name}}
spec:
  selector:
    app: {{ .Values.mongo.name}}
  ports:
    - port: {{ .Values.mongo.port}}
      targetPort: {{ .Values.mongo.targetPort}}
