apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volumes.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volumes.storage }}
