apiVersion: v1
kind: Service
metadata:
  name: student-app-client-service
spec:
  selector:
    app: {{ .value.client.name}}
  ports:
    - port: {{ .value.client.port}}
      protocol: TCP
      targetPort: {{ .value.client.targetPort}}
  type: ClusterIP
