apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .value.client.name }}
spec:
  selector:
    matchLabels: {{ include "common.client" . | nindent 6}}
  replicas: 1
  template:
    metadata:
      labels: {{ include "common.client" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .value.client.name }}
          image: {{ .value.client.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .value.client.port }}
